import type { PropertyType } from "./types"

export function getSaudiProperties(): PropertyType[] {
  return [
    {
      id: "prop1",
      address: "King Fahd Road, Riyadh",
      city: "Riyadh",
      region: "Riyadh Region",
      price: 1200000,
      bedrooms: 4,
      bathrooms: 3,
      sqft: 2500,
      type: "Villa",
      imageUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-FMSTK7fAWD1Y5t4JypF9mnWthfxfTH.png",
      lat: 24.7136,
      lng: 46.6753,
      isFeatured: true,
      isCertified: true,
      description: "Luxurious villa with modern amenities, private pool, and garden in an exclusive neighborhood.",
    },
    {
      id: "prop2",
      address: "Tahlia Street, Jeddah",
      city: "Jeddah",
      region: "Makkah Region",
      price: 950000,
      bedrooms: 3,
      bathrooms: 2,
      sqft: 1800,
      type: "Apartment",
      imageUrl: "/placeholder.svg?height=600&width=800&text=Modern+Apartment",
      lat: 21.5433,
      lng: 39.1728,
      isCertified: true,
    },
    {
      id: "prop3",
      address: "Corniche Road, Dammam",
      city: "Dammam",
      region: "Eastern Province",
      price: 1500000,
      bedrooms: 5,
      bathrooms: 4,
      sqft: 3200,
      type: "Villa",
      imageUrl: "/placeholder.svg?height=600&width=800&text=Waterfront+Villa",
      lat: 26.4207,
      lng: 50.0888,
      isFeatured: true,
    },
    {
      id: "prop4",
      address: "Prince Sultan Road, Riyadh",
      city: "Riyadh",
      region: "Riyadh Region",
      price: 850000,
      bedrooms: 3,
      bathrooms: 2,
      sqft: 1600,
      type: "Apartment",
      imageUrl: "/placeholder.svg?height=300&width=400&text=Urban+Apartment",
      lat: 24.7741,
      lng: 46.7388,
    },
    {
      id: "prop5",
      address: "Al Khobar Corniche, Al Khobar",
      city: "Al Khobar",
      region: "Eastern Province",
      price: 1800000,
      bedrooms: 4,
      bathrooms: 3,
      sqft: 2800,
      type: "Penthouse",
      imageUrl: "/placeholder.svg?height=300&width=400&text=Luxury+Penthouse",
      lat: 26.2794,
      lng: 50.2083,
      isFeatured: true,
      isCertified: true,
    },
    {
      id: "prop6",
      address: "Al Andalus District, Jeddah",
      city: "Jeddah",
      region: "Makkah Region",
      price: 750000,
      bedrooms: 2,
      bathrooms: 2,
      sqft: 1400,
      type: "Apartment",
      imageUrl: "/placeholder.svg?height=300&width=400&text=Cozy+Apartment",
      lat: 21.4858,
      lng: 39.1925,
    },
    {
      id: "prop7",
      address: "Diplomatic Quarter, Riyadh",
      city: "Riyadh",
      region: "Riyadh Region",
      price: 2200000,
      bedrooms: 5,
      bathrooms: 4,
      sqft: 3500,
      type: "Villa",
      imageUrl: "/placeholder.svg?height=300&width=400&text=Premium+Villa",
      lat: 24.7,
      lng: 46.6221,
      isFeatured: true,
      isCertified: true,
    },
    {
      id: "prop8",
      address: "Al Rawdah District, Jeddah",
      city: "Jeddah",
      region: "Makkah Region",
      price: 1100000,
      bedrooms: 3,
      bathrooms: 3,
      sqft: 2100,
      type: "Townhouse",
      imageUrl: "/placeholder.svg?height=300&width=400&text=Modern+Townhouse",
      lat: 21.5697,
      lng: 39.1243,
      isCertified: true,
    },
  ]
}
